version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    #command: ["./bin/thrust", "./bin/rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
      - "80:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/listen2me
      RAILS_ENV: development
      SECRET_KEY_BASE: development_key_123
      TARGET_PORT: 3000
      DEBUG: "true"

volumes:
  postgres_data:
  bundle_cache: 